/* Generated by make_tables.py from bf_to_aheui.py -- do not edit. */
#ifndef AHEUI_TABLES_H
#define AHEUI_TABLES_H

/* Symbol alphabet: a PNG stores each cell as a byte whose residue
 * mod 40 indexes this table. Residue 39 ends the data. */
#define AH_BASE      40
#define AH_TERM      39
#define AH_NALPHA    38
static const unsigned short ah_alphabet[AH_NALPHA] = {
  0x000A, 0x0020, 0xB098, 0xB2E4, 0xB354, 0xB450, 0xB530, 0xB5A0, 0xB8E8, 0xBA38, 0xBB34, 0xBB4F, 0xBC1B, 0xBC1C, 0xBC1F, 0xBC20, 0xBC25, 0xBC93, 0xBC9D, 0xBD80, 0xBD97, 0xBD9B, 0xBE60, 0xBFCC, 0xC03C, 0xC218, 0xC219, 0xC21C, 0xC2F9, 0xC2FC, 0xC464, 0xC544, 0xC5B4, 0xC624, 0xC6B0, 0xCD08, 0xCD94, 0xD76C
};

/* Scaffold cells used by the loop frames. */
#define AH_DUP_SKIP2   0xC03C
#define AH_NOOP_RIGHT  0xC544
#define AH_NOOP_LEFT   0xC5B4
#define AH_NOOP_DOWN   0xC6B0
#define AH_NOOP_UP     0xC624
#define AH_CHECK_DOWN  0xCD94
#define AH_CHECK_UP    0xCD08
#define AH_BLOCK_BEGIN 0xBD80
#define AH_BLOCK_HALT  0xD76C

/* Leaf blocks, each a NULL-terminated list of 0-terminated rows. */
static const unsigned short block_plus_0[] = { 0xBC1C, 0xBC1C, 0xB098, 0xB2E4, 0xBD97, 0 };
static const unsigned short block_plus_1[] = { 0xB8E8, 0xB5A0, 0xB5A0, 0xBC93, 0xBC93, 0 };
static const unsigned short *const block_plus[] = { block_plus_0, block_plus_1, 0 };
static const unsigned short block_minus_0[] = { 0xBC1F, 0xBC20, 0xBC25, 0xB530, 0xB530, 0xBC1B, 0xB450, 0 };
static const unsigned short block_minus_1[] = { 0xB8E8, 0xB5A0, 0xB5A0, 0xBC93, 0xBC93, 0xBC9D, 0xB354, 0 };
static const unsigned short *const block_minus[] = { block_minus_0, block_minus_1, 0 };
static const unsigned short block_out_0[] = { 0xBFCC, 0 };
static const unsigned short block_out_1[] = { 0xBB4F, 0 };
static const unsigned short *const block_out[] = { block_out_0, block_out_1, 0 };
static const unsigned short block_in_0[] = { 0xBB34, 0 };
static const unsigned short block_in_1[] = { 0xBD9B, 0 };
static const unsigned short *const block_in[] = { block_in_0, block_in_1, 0 };
static const unsigned short block_right_0[] = { 0xC2F9, 0xC21C, 0 };
static const unsigned short block_right_1[] = { 0xC218, 0xBE60, 0xC464, 0 };
static const unsigned short block_right_2[] = { 0xBD80, 0xC218, 0xBA38, 0 };
static const unsigned short block_right_3[] = { 0xC6B0, 0xC5B4, 0 };
static const unsigned short *const block_right[] = { block_right_0, block_right_1, block_right_2, block_right_3, 0 };
static const unsigned short block_left_0[] = { 0xC2FC, 0xC219, 0 };
static const unsigned short block_left_1[] = { 0xC218, 0xBE60, 0xC464, 0 };
static const unsigned short block_left_2[] = { 0xBD80, 0xC218, 0xBA38, 0 };
static const unsigned short block_left_3[] = { 0xC6B0, 0xC5B4, 0 };
static const unsigned short *const block_left[] = { block_left_0, block_left_1, block_left_2, block_left_3, 0 };

typedef struct { char tok; const unsigned short *const *rows; } ah_leaf;
static const ah_leaf ah_leaves[] = {
  { '+', block_plus },
  { '-', block_minus },
  { '.', block_out },
  { ',', block_in },
  { '>', block_right },
  { '<', block_left },
  { 0, 0 }
};

#endif
