#!/usr/bin/env python3
"""
make_tables.py [out.h]

Emits the alphabet and the Brainfuck leaf blocks as a C header, from
bf_to_aheui.py. The libretro core is the third copy of these tables after the
Python compiler and the console page, and the same rule applies to all three:
none of them is typed by hand. Run this after any change to bf_to_aheui.py.
"""
import sys

import bf_to_aheui as C
from sync_console import LEAVES, SCAFFOLD, alphabet


def cps(s):
    return ', '.join('0x%04X' % ord(c) for c in s)


def main(out='aheui_tables.h'):
    a = alphabet()
    L = []
    L.append('/* Generated by make_tables.py from bf_to_aheui.py -- do not edit. */')
    L.append('#ifndef AHEUI_TABLES_H')
    L.append('#define AHEUI_TABLES_H')
    L.append('')
    L.append('/* Symbol alphabet: a PNG stores each cell as a byte whose residue')
    L.append(' * mod 40 indexes this table. Residue 39 ends the data. */')
    L.append('#define AH_BASE      40')
    L.append('#define AH_TERM      39')
    L.append('#define AH_NALPHA    %d' % len(a))
    L.append('static const unsigned short ah_alphabet[AH_NALPHA] = {')
    L.append('  %s' % cps(a))
    L.append('};')
    L.append('')
    L.append('/* Scaffold cells used by the loop frames. */')
    for name in SCAFFOLD:
        L.append('#define AH_%-11s 0x%04X' % (name, ord(getattr(C, name))))
    L.append('#define AH_BLOCK_BEGIN 0x%04X' % ord(C.BLOCK_BEGIN[0]))
    L.append('#define AH_BLOCK_HALT  0x%04X' % ord(C.BLOCK_HALT[0]))
    L.append('')
    L.append('/* Leaf blocks, each a NULL-terminated list of 0-terminated rows. */')
    names = []
    for tok, name in LEAVES:
        rows = getattr(C, name)
        low = name.lower()
        for i, r in enumerate(rows):
            L.append('static const unsigned short %s_%d[] = { %s, 0 };' % (low, i, cps(r)))
        L.append('static const unsigned short *const %s[] = { %s, 0 };'
                 % (low, ', '.join('%s_%d' % (low, i) for i in range(len(rows)))))
        names.append((tok, low))
    L.append('')
    L.append('typedef struct { char tok; const unsigned short *const *rows; } ah_leaf;')
    L.append('static const ah_leaf ah_leaves[] = {')
    for tok, low in names:
        L.append("  { '%s', %s }," % (tok, low))
    L.append('  { 0, 0 }')
    L.append('};')
    L.append('')
    L.append('#endif')
    open(out, 'w').write('\n'.join(L) + '\n')
    print(f'{out}: {len(a)} symbols, {len(names)} leaf blocks')


if __name__ == '__main__':
    main(*(sys.argv[1:] or []))
